### ISSUE TITLE
Ectoo.max(Repo, Candidate, :id) gives "** (ArithmeticError) bad argument in arithmetic expression"

### ISSUE THREAD

**Issue by vraravam** [henrik/ectoo#3]
I'm not sure why, but this only fails for the first call in the spec. The second call to `Ectoo.max/3` always passes. Also, I have used `Ectoo.count/2` without any issues.

**Comment by henrik** [comment]
@vraravam Thank you for the report! Could you show the code that fails and succeeds with some context, and the full backtrace?

**Comment by vraravam** [comment]
```
it "when candidate id not present in candidates table" do
      # TODO: Not sure why Ectoo.max(Repo, Candidate, :id) is failing - need to investigate
      current_candidate_count = Ectoo.max(Repo, Candidate, :id)
      # current_candidate_count = Ectoo.count(Repo, Candidate)
```

This last uncommented-line throws the error with the following stacktrace:

```
    ** (ArithmeticError) bad argument in arithmetic expression
    spec/models/candidate_interview_schedule_spec.exs:66: RecruitxBackend.CandidateInterviewScheduleSpec.example_when_candidate_id_not_present_in_candidates_table_azyfueimnrgwtbodckxlhqpvjs/1
    (espec) lib/espec/example_runner.ex:33: ESpec.ExampleRunner.run_example/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (espec) lib/espec/runner.ex:69: ESpec.Runner.run_examples/1
    (espec) lib/espec/runner.ex:42: ESpec.Runner.do_run/2
    (espec) lib/espec/runner.ex:28: ESpec.Runner.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
```

**Comment by henrik** [comment]
@vraravam Hm, thank you. So line 66 is the one assigning the count? If you remove everything else from that file so it just has a test that assigns the count to a variable and nothing else (no assertions etc), do you still get the error?

It doesn't sound like the error should be due to this line so I want to make sure it is.

I see you're using ESpec – maybe it does something weird.

Something else that might help if you want to debug this: you can edit Ectoo's code within your project in `deps/ectoo/lib/ectoo.ex` and do `MIX_ENV=test mix deps.compile ectoo` to recompile it.

**Comment by vraravam** [comment]
Yes - even with everything else removed, and only the barebones test method alone, the same issue occurred. What's interesting was that the 2nd call passed on my OSX, while in our CI server (linux), even that failed. So I had to not use the `Ectoo.max/3` call.

**Comment by henrik** [comment]
@vraravam That's interesting. I do run Ectoo tests in a Linux CI and those pass: https://travis-ci.org/henrik/ectoo

I'm afraid I don't have much to go on currently :/ If there's any chance that you could reproduce the issue in the Ectoo test suite, that would be immensely helpful. Or if you could reduce your project to the minimal thing that fails and put that somewhere so I could run it. I realize this would be some trouble for you.

Another idea would be for you to add debug stuff to Ectoo (see my instructions above) and see if you can get closer to figuring out where it goes wrong.
